# Generated by Django 2.1.7 on 2019-02-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_sales', models.CharField(max_length=100)),
                ('total_hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sheet_id', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
                ('hourly_rate', models.CharField(max_length=100)),
                ('declared_tips', models.CharField(max_length=100)),
                ('adjusted_tips', models.CharField(max_length=100)),
                ('total_tips', models.CharField(max_length=100)),
                ('sales', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('total_hours', models.CharField(max_length=100)),
                ('total_tip', models.CharField(max_length=100)),
                ('total_sales', models.CharField(max_length=100)),
                ('time_Sheets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TimeSheet')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='workers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Worker'),
        ),
    ]
