# Generated by Django 2.1.7 on 2019-02-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190226_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='workers',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.Worker'),
            preserve_default=False,
        ),
    ]
