# Generated by Django 2.1.7 on 2019-02-26 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190226_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.AutoField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='time_sheet_pos_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='worker_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='main.Worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='restaurant_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='main.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time_sheet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
