# Generated by Django 2.1.7 on 2019-02-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_worker_time_sheets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='time_sheet_id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='id',
            field=models.AutoField(auto_created=True, default=6, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='id',
            field=models.AutoField(auto_created=True, default=7, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='worker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='main.Worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='main.Restaurant'),
        ),
    ]
