# Generated by Django 2.1.7 on 2019-02-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190226_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='restaurant_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='main.Restaurant'),
        ),
    ]
