# Generated by Django 2.1.7 on 2019-02-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190226_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='worker_id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='worker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_worker', to='main.Worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='worker_restaurant', to='main.Restaurant'),
        ),
    ]
